name: Openwrt CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-workflow-local-docker-image:
    uses: pheoxy/openwrt-camelot/.github/workflows/1-docker-publish.yml@main
  build-target:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pheoxy/openwrt-camelot:main
      env:
        BUILD_TARGET: archerc7v2
        OLD_CONFIG: y
        EXTRA_CONFIG: n
        MENU_CONFIG: n
        DEBUG: n
      volumes:
        - /output:/home/openwrt-builder/output
    steps:
    - uses: actions/checkout@v3
    - name: Build the target in the openwrt-builder container
      run: /bin/bash -c "/home/openwrt-builder/source/build.sh"
