name: Openwrt CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    name: Manual

jobs:
  call-workflow-local-docker-image:
    uses: pheoxy/openwrt-camelot/.github/workflows/1-docker-publish.yml@main
  build-target:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pheoxy/openwrt-camelot:main
    steps:
    - name: Build the target in the openwrt-builder container
      run: /bin/bash -c "cd /home/openwrt-builder/source && \
           cp archerc7v2/.config .config && \
           make defconfig && \
           make"
